### ISSUE TITLE
Not fullscreen

### ISSUE THREAD

**Issue by Simon423** [GarrettBlackmon/youtube-cast-receiver#3]
![image](https://user-images.githubusercontent.com/20999010/156482811-fdf3bbba-a93f-427b-971e-99437888187a.png)
Not entirely fullscreen. It would be great if there's a solution to remove the top layer. Thank you

**Comment by GarrettBlackmon** [comment]
Hmm, thanks for the heads up. This appears to be due to youtube.com/tv expecting a 16:9 aspect ratio. The menu bar at the top of the window is taking up some vertical space causing horizontal padding.

Which platform is this occurring on?

**Comment by Simon423** [comment]
Thank you for the reply. I’m on windows 11

**Comment by GarrettBlackmon** [comment]
Fixed in release [1.0.1](https://github.com/GarrettBlackmon/youtube-cast-receiver/releases/tag/v1.0.1)

Enjoy :)
