### ISSUE TITLE
Feature request: release for android

### ISSUE THREAD

**Issue by marcomow** [GarrettBlackmon/youtube-cast-receiver#8]
Great project!

It would be great if this app would be possible to be built also for android, this would allow millions of old android phones to become chromecasts!

**Comment by GarrettBlackmon** [comment]
I actually have done this long ago and it did work!

I see this is very old but if I can find the APK I'll add it to the releases page.

**Comment by GarrettBlackmon** [comment]
@marcomow https://github.com/GarrettBlackmon/youtube-cast-receiver/releases/tag/v1.0.1

Found it! the reason I didn't release it is it's locked to a 16:9 aspect ratio which doesnt fit most mobile devices well, I don't have a device with HDMI out but I imagine it will scale correctly when plugged into an external display.

Please let me know!

Also, clearly for an android app the codebase is different, but I uploaded it anyway incase you want to make use of it.

**Comment by marcomow** [comment]
Amazing @GarrettBlackmon ! I'll test and let you know!

**Comment by GarrettBlackmon** [comment]
> Amazing @GarrettBlackmon ! I'll test and let you know!

You've inspired me to give it another look and it actually looks perfectly fine on my pixel tablet!![PXL_20240919_142038504.jpg](https://github.com/user-attachments/assets/a155c5da-4358-44a9-9b7a-80d254909dea)

**Comment by marcomow** [comment]
yes, it works! I've just tested using my phone as both receiver and controller and no issues (aside from the weird setup)

Do you think it would be complicated to unlock the display ratio?

**Comment by GarrettBlackmon** [comment]
> Do you think it would be complicated to unlock the display ratio?

Unfortunately, it'd be impossible as youtube.com/tv is set at a fixed aspect ratio of 16:9 and not responsive. I suppose the engineers that built it figured that would be easier since this should only ever be accessed from smart TVs which would be 16:9 always.


Here's what it looks like when I resize my browser.
![image](https://github.com/user-attachments/assets/946739af-37c2-4d91-805b-171e0e2e9056)

**Comment by marcomow** [comment]
Hey @GarrettBlackmon FYI I've played around and ported the codebase to Deno, with builds for various systems (not yet building for android tho). 
I've had some troubles with forking, so I've just created a new repo. Nevertheless, I've credited you in the README. 
https://github.com/marcomow/youtube-cast-receiver
Thanks for your great project!

**Comment by GarrettBlackmon** [comment]
> Hey @GarrettBlackmon FYI I've played around and ported the codebase to Deno, with builds for various systems (not yet building for android tho). 
> I've had some troubles with forking, so I've just created a new repo. Nevertheless, I've credited you in the README. 
> https://github.com/marcomow/youtube-cast-receiver
> Thanks for your great project!

Dude!!! That's awesome! What are the benefits of building with deno as opposed to electron? I just picked whatever seemed easiest to get a tiny mvp out at the time. Really happy to see someone running with this!

I think the ultimate final form would be the suggestion made in open issues to make it a service so you can cast to your pc at any time without having to open the app first. Seems a lot more difficult to detect when a video starts playing and maximize the app in the foreground.

**Comment by marcomow** [comment]
thanks! 
Deno is my personal preference for many reasons, mostly the developer experience is awesome, no need of a patchwork of many dependencies; if you look at my codebase the only real "external" deps are puppeteer (to launch browser with agent string) and the zip utility...all the rest is built-in, even the compiler.

Probably the builds are quite fat (they're working on it) but at the present moment I don't care that much, it was more of a project for fun. 

Making this a service is a completely different thing as far as I understand, and honestly I don't see the benefit of such effort when launching the app is no big deal
