### ISSUE TITLE
error when  install on raspberry pi 4b

### ISSUE THREAD

**Issue by piotrek2555** [GarrettBlackmon/youtube-cast-receiver#9]
dpkg: error processing archive youtube-cast-receiver_1.0.1_amd64.deb (--install):
 package architecture (amd64) does not match system (armhf)

**Comment by GarrettBlackmon** [comment]
Ah, I see this is very old but, but to answer why this is, this app is built for a 64bit architecture while the RPI uses ARM architecture.

There is no reason this can't be compiled for an ARM CPU but you'd need to build from source yourself. Interesting use-case, never considered running this on a Pi to built a DIY chromecast.
